# Generated by Django 6.0 on 2026-01-04 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogical', '0002_quiz_progress_quiz_quizassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(default='diagnostic', help_text="Type d'évaluation: diagnostic, formative, etc.", max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(limit_choices_to={'user_type': 'apprenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_sessions', to='pedagogical.quiz')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.JSONField(default=list, help_text="Forces identifiées (ex: ['logique', 'raisonnement'])")),
                ('weaknesses', models.JSONField(default=list, help_text="Fragilités probables (ex: ['lecture', 'attention'])")),
                ('learning_style', models.CharField(default='', help_text="Style d'apprentissage: visuel/logique/guidé", max_length=100)),
                ('confidence_level', models.CharField(choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('élevé', 'Élevé')], default='moyen', max_length=20)),
                ('recommendations', models.JSONField(default=list, help_text='Recommandations pédagogiques')),
                ('analysis_data', models.JSONField(default=dict, help_text="Données complètes de l'analyse (indicateurs, patterns)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(limit_choices_to={'user_type': 'apprenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profile', to=settings.AUTH_USER_MODEL)),
                ('last_evaluation_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_profiles', to='pedagogical.evaluationsession')),
            ],
            options={
                'verbose_name_plural': 'Cognitive Profiles',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text='Identifiant de la question', max_length=255)),
                ('question_text', models.TextField(help_text='Texte de la question')),
                ('question_type', models.CharField(default='qcm', max_length=50)),
                ('competence_type', models.CharField(choices=[('lecture', 'Lecture'), ('logique', 'Logique'), ('calcul', 'Calcul'), ('comprehension', 'Compréhension'), ('attention', 'Attention')], default='comprehension', max_length=50)),
                ('answer', models.TextField(help_text="Réponse de l'élève")),
                ('correct_answer', models.TextField(help_text='Réponse correcte')),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_ms', models.IntegerField(help_text='Temps de réponse en millisecondes')),
                ('attempts', models.IntegerField(default=1, help_text='Nombre de tentatives')),
                ('help_used', models.BooleanField(default=False, help_text='Aide utilisée')),
                ('help_type', models.CharField(blank=True, help_text="Type d'aide utilisée", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='pedagogical.evaluationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
